###### Importing Numpy

In [1]:
import numpy as np #as means alias

###### Numpy Arrays


* Vectors: 1-D arrays
* Matrices: 2-D arrays

In [3]:
my_list = [1,2,3]
my_array = np.array(my_list)
my_array

array([1, 2, 3])

In [4]:
type(my_list)

list

In [5]:
type(my_array)

numpy.ndarray

In [6]:
my_list_2 = [[1,2,3],[4,5,6],[7,8,9]]
my_list_2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_list_2) #2d array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### Built-in Methods to create array

In [8]:
#arange

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,7)

array([3, 4, 5, 6])

In [10]:
np.arange(4,27,4)

array([ 4,  8, 12, 16, 20, 24])

In [11]:
#zeros

np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((1,3))

array([[0., 0., 0.]])

In [12]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
#linspace : return evenly spaced numbers over a specified interval

np.linspace(0,2,13)

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        , 1.16666667, 1.33333333, 1.5       ,
       1.66666667, 1.83333333, 2.        ])

In [27]:
np.linspace(0,2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [28]:
#eye : create identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###### Random

In [34]:
#rand : create an array of given shape and populates it with random samples from a uniform distribution over [0,1)

np.random.rand(5)

array([0.66232612, 0.41967793, 0.63415668, 0.00268707, 0.79235503])

In [37]:
np.random.rand(3,4)

array([[0.56589361, 0.84747016, 0.80110384, 0.48166247],
       [0.27064733, 0.46024588, 0.87788929, 0.90916248],
       [0.192799  , 0.42897994, 0.17656268, 0.09949708]])

In [50]:
#randint : random integers from low(inclusive) to high (exclusive)
np.random.randint(1,507098)

417296

In [54]:
np.random.randint(1,507098,16)

array([266290, 465104, 290289, 244633, 241717, 433224,   5852, 312561,
       432496, 360392,  16106, 427321, 294296, 205008, 244419, 325415])

In [55]:
#randn : return a sample(s) from standard normal distribution (sigma =1) 

np.random.randn(2)

array([-1.12664166,  0.79866271])

In [60]:
np.random.randn(3,4)

array([[ 1.38709955,  0.11889941,  1.06920291, -2.31633733],
       [-0.32784966, -1.33728425, -1.31630226,  1.05213211],
       [ 0.78237902,  1.73889003,  0.43920256, -0.20498038]])

In [64]:
np.random.sample(30)

array([0.92838024, 0.30730013, 0.44001942, 0.06263892, 0.31990579,
       0.64452626, 0.5927072 , 0.38541051, 0.29124157, 0.05322669,
       0.30119347, 0.56892081, 0.74210586, 0.37007231, 0.17370143,
       0.74012864, 0.3602458 , 0.54025815, 0.96768582, 0.19262497,
       0.84908282, 0.639262  , 0.79918892, 0.77453796, 0.18162808,
       0.21546574, 0.77158074, 0.32984608, 0.78309027, 0.09787203])

In [96]:
#seed : used to set 'random state'

np.random.seed(50)
np.random.randint(1,200,20)

array([177, 140, 110,  34, 133,  71,  71,  23, 134,   3,  96,  72, 112,
       197, 164,  93,  92, 155, 135, 149])

In [82]:
np.random.seed(6)
np.random.rand(3,4)

array([[0.89286015, 0.33197981, 0.82122912, 0.04169663],
       [0.10765668, 0.59505206, 0.52981736, 0.41880743],
       [0.33540785, 0.62251943, 0.43814143, 0.73588211]])

##### Arrays Attributes and Methods

In [92]:
ran = np.arange(21)
ranar = np.random.randint(0,60,10)

In [93]:
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [94]:
ranar

array([21, 36, 50, 24, 31, 40, 13, 39, 56, 16])

In [97]:
#reshape
ran.reshape(3,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [105]:
re_ranar = ranar.reshape(2,5)
re_ranar

array([[21, 36, 50, 24, 31],
       [40, 13, 39, 56, 16]])

###### max, min, argmax, argmin

In [99]:
ranar

array([21, 36, 50, 24, 31, 40, 13, 39, 56, 16])

In [100]:
ranar.max()

56

In [101]:
ranar.min()

13

In [102]:
ranar.argmax()

8

In [103]:
ranar.argmin()

6

###### shape

attribute (not a method) that arrays have 

In [104]:
ranar.shape

(10,)

In [107]:
re_ranar.shape

(2, 5)

In [109]:
ranar

array([21, 36, 50, 24, 31, 40, 13, 39, 56, 16])

In [111]:
re_ranar1 = ranar.reshape(10,1)
re_ranar1

array([[21],
       [36],
       [50],
       [24],
       [31],
       [40],
       [13],
       [39],
       [56],
       [16]])

In [112]:
re_ranar1.shape

(10, 1)

In [113]:
ranar

array([21, 36, 50, 24, 31, 40, 13, 39, 56, 16])

In [114]:
ranar.shape

(10,)

In [116]:
re_ranar1

array([[21],
       [36],
       [50],
       [24],
       [31],
       [40],
       [13],
       [39],
       [56],
       [16]])

In [117]:
re_ranar1.shape

(10, 1)

In [118]:
re_ranar

array([[21, 36, 50, 24, 31],
       [40, 13, 39, 56, 16]])

In [119]:
re_ranar.shape

(2, 5)