In [1]:
import numpy as np

In [2]:
arr = np.arange(0,41,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

#### Bracket Indexing and Selection

In [3]:
arr[2]

6

In [4]:
arr[2:6]

array([ 6,  9, 12, 15])

###### Broadcasting

In [5]:
arr[0:5] = 100

arr

array([100, 100, 100, 100, 100,  15,  18,  21,  24,  27,  30,  33,  36,
        39])

In [6]:
arr = np.arange(0,41,3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [7]:

slice_of_arr = arr[0:6]
slice_of_arr

array([ 0,  3,  6,  9, 12, 15])

In [8]:
slice_of_arr[:] = 99

In [9]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [10]:
arr

array([99, 99, 99, 99, 99, 99, 18, 21, 24, 27, 30, 33, 36, 39])

Data is not copied, its a view of the original array!! This avoids memory problem. 

To get a copy, we need to be explicit by using arr.copy()

What if it was list?

In [11]:
lst1=[i for i in range(21)]
lst1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [12]:
slice_of_lst1 = lst1[0:6]
slice_of_lst1

[0, 1, 2, 3, 4, 5]

In [13]:
slice_of_lst1[:] = [90,90,90,90,90]
slice_of_lst1

[90, 90, 90, 90, 90]

In [14]:
lst1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [15]:
#copy

arr = np.arange(0,41,3)
arr1 = arr.copy()

In [16]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [17]:
arr1

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

In [18]:

slice_of_arr = arr1[0:6]
slice_of_arr

array([ 0,  3,  6,  9, 12, 15])

In [19]:
slice_of_arr[:] = 99

In [20]:
arr1

array([99, 99, 99, 99, 99, 99, 18, 21, 24, 27, 30, 33, 36, 39])

In [21]:
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39])

###### Indexing a 2D array

In [22]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [23]:
#indexing a row

arr_2d[2]

array([35, 40, 45])

In [24]:
#get individual element

arr_2d[2][0]

35

In [25]:
arr_2d[2,0]

35

In [26]:
arr_2d[0,2]

15

In [27]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

* Create a array of shape 4 by 5
* perform 5 indexing
* perform 5 slicing

In [31]:
ar1 = np.arange(1,41,2).reshape(4,5)
ar1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [32]:
ar1[2]

array([21, 23, 25, 27, 29])

In [33]:
ar1[-2]

array([21, 23, 25, 27, 29])

In [34]:
ar1[2][3]

27

In [38]:
ar1[2,-2]

27

In [36]:
ar1[-2][3]

27

In [37]:
ar1[-2][-2]

27

In [40]:
ar1[-3,-4]

13

In [41]:
ar1[-3,1]

13

In [42]:
ar1[1,-4]

13

In [43]:
ar1[1,1]

13

In [44]:
ar1

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39]])

In [46]:
ar1[1:3,2:4]

array([[15, 17],
       [25, 27]])

In [49]:
ar1[-3:3,2:-1]

array([[15, 17],
       [25, 27]])

In [54]:
ar1[:3,1:4]

array([[ 3,  5,  7],
       [13, 15, 17],
       [23, 25, 27]])

In [55]:
ar1[:-1,-4:-1]

array([[ 3,  5,  7],
       [13, 15, 17],
       [23, 25, 27]])

In [56]:
ar1[:3,-4:4]

array([[ 3,  5,  7],
       [13, 15, 17],
       [23, 25, 27]])

###### Conditional Selection

In [57]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
bool_arr = arr > 4

In [60]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [61]:
arr[bool_arr == False] 

array([1, 2, 3, 4])

In [62]:
arr[bool_arr == True] 

array([ 5,  6,  7,  8,  9, 10])

In [63]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [64]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[arr > 9/4]

array([ 3,  4,  5,  6,  7,  8,  9, 10])