In [1]:
import numpy as np

arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [3]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [5]:
arr/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2480/1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [6]:
1/arr

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2480/255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [8]:
arr**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

###### Universal Array Functions

In [9]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
#exponential
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [12]:
#Trigonometric Functions like sine
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [13]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [14]:
a = np.array([[1, 0],
              [0, 1]])

In [18]:
b = np.array([[4, 1,7],
              [2, 2,3]])

In [19]:
np.matmul(a, b)

array([[4, 1, 7],
       [2, 2, 3]])

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.log10(arr)

/var/folders/wl/v3x3g82n3b38s3cvwvtr0r7h0000gn/T/ipykernel_2480/2153533263.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [23]:
arr.mean()

4.5

In [24]:
arr.max()

9

In [25]:
arr.min()

0

In [26]:
arr.shape

(10,)

In [27]:
arr.var()

8.25

In [28]:
arr.std()

2.8722813232690143

###### Axis Logic

* axis 0 : vertical axis (rows)
* axis 1 : horizontal axis (columns)

In [31]:
arr_2d = np.arange(1,13).reshape(3,4)
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr_2d.sum()

78

In [36]:
arr_2d.max(axis=0) 

array([ 9, 10, 11, 12])

In [37]:
arr_2d.mean(axis=1)

array([ 2.5,  6.5, 10.5])

1. array of 25 random numbers sampled from std normal distribution
2. array of 25 linearly spaced points between 0 and 1
3. reshape array of point 2 in 5*5 matrix
4. grab all the rows and columns of mat in point 3 baring the corner ones.
5. get the sum of all the columns of mat in point 3

In [38]:
#1
np.random.randn(25)

array([-1.0290265 ,  0.01017091, -0.76608551, -0.41024654, -0.15825894,
        1.40155245,  1.43156535,  0.0404952 ,  0.62847769,  1.45599705,
       -0.79094367, -0.00572162, -1.63292881, -0.01454878, -0.48247898,
       -1.11660363, -0.60250785, -0.46163494,  1.10059876, -1.4614065 ,
        1.08830487, -0.50826419, -0.00802548,  0.51331022,  1.0611313 ])

In [39]:
#2
np.linspace(0,1,25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [41]:
#3
arr3 = np.linspace(0,1,25).reshape(5,5)
arr3

array([[0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667],
       [0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ],
       [0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333],
       [0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667],
       [0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ]])

In [42]:
#4
arr3[1:4,1:4]

array([[0.25      , 0.29166667, 0.33333333],
       [0.45833333, 0.5       , 0.54166667],
       [0.66666667, 0.70833333, 0.75      ]])

In [43]:
#5
arr3.sum(axis=0)

array([2.08333333, 2.29166667, 2.5       , 2.70833333, 2.91666667])